// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.6
// Project name: NMEA2000SailInstrument

#include "ui.h"

lv_obj_t * ui_Depth3;
lv_obj_t * ui_GroundSpeed;
lv_obj_t * ui_WaterSpeed2;
lv_obj_t * ui_AWAneedle;
lv_obj_t * ui_WindLbl3;
lv_obj_t * ui_AWS;
lv_obj_t * ui_ScrAppWind;
lv_obj_t * ui_ScrAppWind = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_AWS = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_WindLbl3 = NULL;
lv_obj_t * ui_AWAneedle = NULL;
lv_obj_t * ui_WaterSpeed2 = NULL;
lv_obj_t * ui_GroundSpeed = NULL;
lv_obj_t * ui_TruWindAngle2 = NULL;
lv_obj_t * ui_Depth3 = NULL;
// event funtions
void ui_event_ScrAppWind(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrAutopilot, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_ScrAutopilot_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrNav, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_ScrNav_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrTruWind, LV_SCR_LOAD_ANIM_MOVE_TOP, 500, 0, &ui_ScrTruWind_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_ScrWind, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 500, 0, &ui_ScrWind_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        DoSetBacklight(e);
    }
}

// build funtions

void ui_ScrAppWind_screen_init(void)
{
    ui_ScrAppWind = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScrAppWind, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label24 = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, -81);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "AWA");
    lv_obj_clear_flag(ui_Label24, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0x828382), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label24, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_ScrAppWind);
    lv_img_set_src(ui_Image5, &ui_img_windcontour_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -4);
    lv_obj_set_y(ui_Image5, -1);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_AWS = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_AWS, 150);
    lv_obj_set_height(ui_AWS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AWS, 0);
    lv_obj_set_y(ui_AWS, 91);
    lv_obj_set_align(ui_AWS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AWS, "--.-");
    lv_obj_clear_flag(ui_AWS, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_AWS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_AWS, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AWS, &ui_font_Arial60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 0);
    lv_obj_set_y(ui_Label26, 53);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "AWS");
    lv_obj_clear_flag(ui_Label26, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindLbl3 = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_WindLbl3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindLbl3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindLbl3, 0);
    lv_obj_set_y(ui_WindLbl3, 133);
    lv_obj_set_align(ui_WindLbl3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindLbl3, "knots");
    lv_obj_set_style_text_color(ui_WindLbl3, lv_color_hex(0x5A595A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WindLbl3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WindLbl3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WindLbl3, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AWAneedle = lv_img_create(ui_ScrAppWind);
    lv_img_set_src(ui_AWAneedle, &ui_img_needle_png);
    lv_obj_set_width(ui_AWAneedle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AWAneedle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AWAneedle, -2);
    lv_obj_set_y(ui_AWAneedle, -65);
    lv_obj_set_align(ui_AWAneedle, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AWAneedle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_img_set_pivot(ui_AWAneedle, 34, 175);

    ui_WaterSpeed2 = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_WaterSpeed2, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_WaterSpeed2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_WaterSpeed2, 8);
    lv_obj_set_y(ui_WaterSpeed2, 436);
    lv_label_set_long_mode(ui_WaterSpeed2, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_WaterSpeed2, "STW --.- kn");
    lv_obj_clear_flag(ui_WaterSpeed2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_WaterSpeed2, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_WaterSpeed2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WaterSpeed2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GroundSpeed = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_GroundSpeed, LV_SIZE_CONTENT);   /// 160
    lv_obj_set_height(ui_GroundSpeed, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_GroundSpeed, -6);
    lv_obj_set_y(ui_GroundSpeed, 436);
    lv_obj_set_align(ui_GroundSpeed, LV_ALIGN_TOP_RIGHT);
    lv_label_set_long_mode(ui_GroundSpeed, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_GroundSpeed, "SOG --.- kn");
    lv_obj_clear_flag(ui_GroundSpeed, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_GroundSpeed, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_align(ui_GroundSpeed, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GroundSpeed, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TruWindAngle2 = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_TruWindAngle2, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_TruWindAngle2, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_TruWindAngle2, 8);
    lv_obj_set_y(ui_TruWindAngle2, 12);
    lv_label_set_text(ui_TruWindAngle2, "TWA ----");
    lv_obj_clear_flag(ui_TruWindAngle2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_TruWindAngle2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TruWindAngle2, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Depth3 = lv_label_create(ui_ScrAppWind);
    lv_obj_set_width(ui_Depth3, LV_SIZE_CONTENT);   /// 150
    lv_obj_set_height(ui_Depth3, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_Depth3, 289);
    lv_obj_set_y(ui_Depth3, 12);
    lv_label_set_text(ui_Depth3, "Depth ---.- m");
    lv_obj_clear_flag(ui_Depth3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_align(ui_Depth3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Depth3, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ScrAppWind, ui_event_ScrAppWind, LV_EVENT_ALL, NULL);
    ui_ScrAppWind = ui_ScrAppWind;
    ui_AWS = ui_AWS;
    ui_WindLbl3 = ui_WindLbl3;
    ui_AWAneedle = ui_AWAneedle;
    ui_WaterSpeed2 = ui_WaterSpeed2;
    ui_GroundSpeed = ui_GroundSpeed;
    ui_Depth3 = ui_Depth3;

}

void ui_ScrAppWind_screen_destroy(void)
{
    if(ui_ScrAppWind) lv_obj_del(ui_ScrAppWind);

    // NULL screen variables
    ui_ScrAppWind = NULL;
    ui_ScrAppWind = NULL;
    ui_Label24 = NULL;
    ui_Image5 = NULL;
    ui_AWS = NULL;
    ui_AWS = NULL;
    ui_Label26 = NULL;
    ui_WindLbl3 = NULL;
    ui_WindLbl3 = NULL;
    ui_AWAneedle = NULL;
    ui_AWAneedle = NULL;
    ui_WaterSpeed2 = NULL;
    ui_WaterSpeed2 = NULL;
    ui_GroundSpeed = NULL;
    ui_GroundSpeed = NULL;
    ui_TruWindAngle2 = NULL;
    ui_Depth3 = NULL;
    ui_Depth3 = NULL;

}
